version: '3'
services:
  go-app:
    build: .
      # context: .
      # dockerfile: go-alpine.Dockerfile
    ports:
     - "8000:8000"
    volumes:
     - ./app:/app-dir
    depends_on:
     - redis
  redis:
    build: 
      context: .
      dockerfile: redis.Dockerfile
    ports:
     - "6379:6379"
  redis-cli:
    image: redis
    links:
     - redis
    command: redis-cli -h redis